#!/usr/bin/env bash
# Prints Best School 8 times.
#Prints bad luck for 4th time
#Prints good luck for 8th time

i=1
while [ $i -lt 11 ]
do
    if [ $i = 4 ]
    then
        echo "bad luck"
    elif [ $i = 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    let i+=1
done
