#!/usr/bin/env bash
# prints numbers from 1 to 20.
# prints 4 and then bad luck from China for the 4th iteration
# prints 9 and then bad luck from Japan for the 9th iteration
# prints 17 and then bad luck from Italy for the 17th iteration


i=1
while [ $i -lt 21 ]
do
    case $i in

        4)
	    echo $i
	    echo "bad luck from China"
	    ;;
	
	9)
	    echo $i
	    echo "bad luck from Japan"
	    ;;
	
	17)
	    echo $i
	    echo "bad luck from Italy"
	    ;;

	*)
	    echo $i
	    ;;
    esac

    let i+=1
done
